# アプリケーション共通設定
spring:
  # アクティブな環境の指定
  # application-{envName}.ymlを必要数用意して、参照させたい環境設定を以下で指定する
  profiles.active: local
  # profiles.active: prod
# サーバ設定
server:
  port: 8080
  servlet:
    # セッションまわりの設定
    session:
      cookie:
        http-only: true
        secure: false
      timeout: 600
# DBまわりの設定
db:
  # 一覧画面の1ページあたりの表示件数
  user:
    list:
      limit: 10
  # DBへの登録制限（大量登録などの攻撃対策）
  restrict:
    user: 50
    account: 30
# ロググループの設定
logging:
  group:
    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
  # 環境間でレベルを変えないロググループの設定はこちらに定義
  level:
    web: INFO
    sql: INFO