package com.user.mng.domain.repository;

import com.user.mng.domain.model.TrnAccount;
import com.user.mng.domain.model.TrnAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrnAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    long countByExample(TrnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    int deleteByExample(TrnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    int insert(TrnAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    int insertSelective(TrnAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    List<TrnAccount> selectByExample(TrnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    TrnAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    int updateByExampleSelective(@Param("record") TrnAccount record, @Param("example") TrnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    int updateByExample(@Param("record") TrnAccount record, @Param("example") TrnAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    int updateByPrimaryKeySelective(TrnAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trn_account
     *
     * @mbg.generated Fri Jun 11 02:01:07 JST 2021
     */
    int updateByPrimaryKey(TrnAccount record);
}