package com.user.mng.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.user.mng.domain.model.TrnUser;
import com.user.mng.domain.model.TrnUserExample;

public interface TrnUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	long countByExample(TrnUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	int deleteByExample(TrnUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	int insert(TrnUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	int insertSelective(TrnUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	List<TrnUser> selectByExample(TrnUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	TrnUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	int updateByExampleSelective(@Param("record") TrnUser record, @Param("example") TrnUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	int updateByExample(@Param("record") TrnUser record, @Param("example") TrnUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	int updateByPrimaryKeySelective(TrnUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	int updateByPrimaryKey(TrnUser record);
}