package com.user.mng.domain.model;

import java.util.Date;

public class TrnAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.id
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.user_name
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.password
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.admin_flg
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private Boolean adminFlg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.remarks
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.insert_user
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private String insertUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.insert_date
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private Date insertDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.update_user
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.update_date
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_account.delete_flg
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	private Boolean deleteFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.id
	 * @return  the value of trn_account.id
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.id
	 * @param id  the value for trn_account.id
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.user_name
	 * @return  the value of trn_account.user_name
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.user_name
	 * @param userName  the value for trn_account.user_name
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.password
	 * @return  the value of trn_account.password
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.password
	 * @param password  the value for trn_account.password
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.admin_flg
	 * @return  the value of trn_account.admin_flg
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public Boolean getAdminFlg() {
		return adminFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.admin_flg
	 * @param adminFlg  the value for trn_account.admin_flg
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setAdminFlg(Boolean adminFlg) {
		this.adminFlg = adminFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.remarks
	 * @return  the value of trn_account.remarks
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.remarks
	 * @param remarks  the value for trn_account.remarks
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.insert_user
	 * @return  the value of trn_account.insert_user
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public String getInsertUser() {
		return insertUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.insert_user
	 * @param insertUser  the value for trn_account.insert_user
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.insert_date
	 * @return  the value of trn_account.insert_date
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.insert_date
	 * @param insertDate  the value for trn_account.insert_date
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.update_user
	 * @return  the value of trn_account.update_user
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.update_user
	 * @param updateUser  the value for trn_account.update_user
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.update_date
	 * @return  the value of trn_account.update_date
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.update_date
	 * @param updateDate  the value for trn_account.update_date
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_account.delete_flg
	 * @return  the value of trn_account.delete_flg
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_account.delete_flg
	 * @param deleteFlg  the value for trn_account.delete_flg
	 * @mbg.generated  Sun Jun 20 17:13:56 JST 2021
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}
}