package com.user.mng.domain.model;

import java.util.Date;

public class TrnUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.id
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.last_name
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.first_name
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.last_name_kana
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String lastNameKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.first_name_kana
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String firstNameKana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.gender
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.birthday
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.postal_code
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String postalCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.prefecture
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String prefecture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.address1
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String address1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.address2
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String address2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.address3
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String address3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.address4
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String address4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.phone_number
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.remarks
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.insert_user
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String insertUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.insert_date
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private Date insertDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.update_user
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.update_date
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column trn_user.delete_flg
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	private Boolean deleteFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.id
	 * @return  the value of trn_user.id
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.id
	 * @param id  the value for trn_user.id
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.last_name
	 * @return  the value of trn_user.last_name
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.last_name
	 * @param lastName  the value for trn_user.last_name
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.first_name
	 * @return  the value of trn_user.first_name
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.first_name
	 * @param firstName  the value for trn_user.first_name
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.last_name_kana
	 * @return  the value of trn_user.last_name_kana
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getLastNameKana() {
		return lastNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.last_name_kana
	 * @param lastNameKana  the value for trn_user.last_name_kana
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setLastNameKana(String lastNameKana) {
		this.lastNameKana = lastNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.first_name_kana
	 * @return  the value of trn_user.first_name_kana
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getFirstNameKana() {
		return firstNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.first_name_kana
	 * @param firstNameKana  the value for trn_user.first_name_kana
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setFirstNameKana(String firstNameKana) {
		this.firstNameKana = firstNameKana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.gender
	 * @return  the value of trn_user.gender
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.gender
	 * @param gender  the value for trn_user.gender
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.birthday
	 * @return  the value of trn_user.birthday
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.birthday
	 * @param birthday  the value for trn_user.birthday
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.postal_code
	 * @return  the value of trn_user.postal_code
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getPostalCode() {
		return postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.postal_code
	 * @param postalCode  the value for trn_user.postal_code
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.prefecture
	 * @return  the value of trn_user.prefecture
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getPrefecture() {
		return prefecture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.prefecture
	 * @param prefecture  the value for trn_user.prefecture
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setPrefecture(String prefecture) {
		this.prefecture = prefecture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.address1
	 * @return  the value of trn_user.address1
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getAddress1() {
		return address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.address1
	 * @param address1  the value for trn_user.address1
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.address2
	 * @return  the value of trn_user.address2
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getAddress2() {
		return address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.address2
	 * @param address2  the value for trn_user.address2
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.address3
	 * @return  the value of trn_user.address3
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getAddress3() {
		return address3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.address3
	 * @param address3  the value for trn_user.address3
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.address4
	 * @return  the value of trn_user.address4
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getAddress4() {
		return address4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.address4
	 * @param address4  the value for trn_user.address4
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setAddress4(String address4) {
		this.address4 = address4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.phone_number
	 * @return  the value of trn_user.phone_number
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.phone_number
	 * @param phoneNumber  the value for trn_user.phone_number
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.remarks
	 * @return  the value of trn_user.remarks
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.remarks
	 * @param remarks  the value for trn_user.remarks
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.insert_user
	 * @return  the value of trn_user.insert_user
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getInsertUser() {
		return insertUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.insert_user
	 * @param insertUser  the value for trn_user.insert_user
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setInsertUser(String insertUser) {
		this.insertUser = insertUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.insert_date
	 * @return  the value of trn_user.insert_date
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.insert_date
	 * @param insertDate  the value for trn_user.insert_date
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.update_user
	 * @return  the value of trn_user.update_user
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.update_user
	 * @param updateUser  the value for trn_user.update_user
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.update_date
	 * @return  the value of trn_user.update_date
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.update_date
	 * @param updateDate  the value for trn_user.update_date
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column trn_user.delete_flg
	 * @return  the value of trn_user.delete_flg
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public Boolean getDeleteFlg() {
		return deleteFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column trn_user.delete_flg
	 * @param deleteFlg  the value for trn_user.delete_flg
	 * @mbg.generated  Sun Jun 20 17:13:57 JST 2021
	 */
	public void setDeleteFlg(Boolean deleteFlg) {
		this.deleteFlg = deleteFlg;
	}
}