package com.user.mng.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TrnUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public TrnUserExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNull() {
			addCriterion("last_name is null");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNotNull() {
			addCriterion("last_name is not null");
			return (Criteria) this;
		}

		public Criteria andLastNameEqualTo(String value) {
			addCriterion("last_name =", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotEqualTo(String value) {
			addCriterion("last_name <>", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThan(String value) {
			addCriterion("last_name >", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThanOrEqualTo(String value) {
			addCriterion("last_name >=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThan(String value) {
			addCriterion("last_name <", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThanOrEqualTo(String value) {
			addCriterion("last_name <=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLike(String value) {
			addCriterion("last_name like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotLike(String value) {
			addCriterion("last_name not like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameIn(List<String> values) {
			addCriterion("last_name in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotIn(List<String> values) {
			addCriterion("last_name not in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameBetween(String value1, String value2) {
			addCriterion("last_name between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotBetween(String value1, String value2) {
			addCriterion("last_name not between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNull() {
			addCriterion("first_name is null");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNotNull() {
			addCriterion("first_name is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNameEqualTo(String value) {
			addCriterion("first_name =", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotEqualTo(String value) {
			addCriterion("first_name <>", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThan(String value) {
			addCriterion("first_name >", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("first_name >=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThan(String value) {
			addCriterion("first_name <", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThanOrEqualTo(String value) {
			addCriterion("first_name <=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLike(String value) {
			addCriterion("first_name like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotLike(String value) {
			addCriterion("first_name not like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIn(List<String> values) {
			addCriterion("first_name in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotIn(List<String> values) {
			addCriterion("first_name not in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameBetween(String value1, String value2) {
			addCriterion("first_name between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotBetween(String value1, String value2) {
			addCriterion("first_name not between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaIsNull() {
			addCriterion("last_name_kana is null");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaIsNotNull() {
			addCriterion("last_name_kana is not null");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaEqualTo(String value) {
			addCriterion("last_name_kana =", value, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaNotEqualTo(String value) {
			addCriterion("last_name_kana <>", value, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaGreaterThan(String value) {
			addCriterion("last_name_kana >", value, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaGreaterThanOrEqualTo(String value) {
			addCriterion("last_name_kana >=", value, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaLessThan(String value) {
			addCriterion("last_name_kana <", value, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaLessThanOrEqualTo(String value) {
			addCriterion("last_name_kana <=", value, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaLike(String value) {
			addCriterion("last_name_kana like", value, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaNotLike(String value) {
			addCriterion("last_name_kana not like", value, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaIn(List<String> values) {
			addCriterion("last_name_kana in", values, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaNotIn(List<String> values) {
			addCriterion("last_name_kana not in", values, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaBetween(String value1, String value2) {
			addCriterion("last_name_kana between", value1, value2, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andLastNameKanaNotBetween(String value1, String value2) {
			addCriterion("last_name_kana not between", value1, value2, "lastNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaIsNull() {
			addCriterion("first_name_kana is null");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaIsNotNull() {
			addCriterion("first_name_kana is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaEqualTo(String value) {
			addCriterion("first_name_kana =", value, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaNotEqualTo(String value) {
			addCriterion("first_name_kana <>", value, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaGreaterThan(String value) {
			addCriterion("first_name_kana >", value, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaGreaterThanOrEqualTo(String value) {
			addCriterion("first_name_kana >=", value, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaLessThan(String value) {
			addCriterion("first_name_kana <", value, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaLessThanOrEqualTo(String value) {
			addCriterion("first_name_kana <=", value, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaLike(String value) {
			addCriterion("first_name_kana like", value, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaNotLike(String value) {
			addCriterion("first_name_kana not like", value, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaIn(List<String> values) {
			addCriterion("first_name_kana in", values, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaNotIn(List<String> values) {
			addCriterion("first_name_kana not in", values, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaBetween(String value1, String value2) {
			addCriterion("first_name_kana between", value1, value2, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andFirstNameKanaNotBetween(String value1, String value2) {
			addCriterion("first_name_kana not between", value1, value2, "firstNameKana");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(String value) {
			addCriterion("gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(String value) {
			addCriterion("gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(String value) {
			addCriterion("gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(String value) {
			addCriterion("gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(String value) {
			addCriterion("gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(String value) {
			addCriterion("gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLike(String value) {
			addCriterion("gender like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotLike(String value) {
			addCriterion("gender not like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<String> values) {
			addCriterion("gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<String> values) {
			addCriterion("gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(String value1, String value2) {
			addCriterion("gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(String value1, String value2) {
			addCriterion("gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterionForJDBCDate("birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterionForJDBCDate("birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andPostalCodeIsNull() {
			addCriterion("postal_code is null");
			return (Criteria) this;
		}

		public Criteria andPostalCodeIsNotNull() {
			addCriterion("postal_code is not null");
			return (Criteria) this;
		}

		public Criteria andPostalCodeEqualTo(String value) {
			addCriterion("postal_code =", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeNotEqualTo(String value) {
			addCriterion("postal_code <>", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeGreaterThan(String value) {
			addCriterion("postal_code >", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeGreaterThanOrEqualTo(String value) {
			addCriterion("postal_code >=", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeLessThan(String value) {
			addCriterion("postal_code <", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeLessThanOrEqualTo(String value) {
			addCriterion("postal_code <=", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeLike(String value) {
			addCriterion("postal_code like", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeNotLike(String value) {
			addCriterion("postal_code not like", value, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeIn(List<String> values) {
			addCriterion("postal_code in", values, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeNotIn(List<String> values) {
			addCriterion("postal_code not in", values, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeBetween(String value1, String value2) {
			addCriterion("postal_code between", value1, value2, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPostalCodeNotBetween(String value1, String value2) {
			addCriterion("postal_code not between", value1, value2, "postalCode");
			return (Criteria) this;
		}

		public Criteria andPrefectureIsNull() {
			addCriterion("prefecture is null");
			return (Criteria) this;
		}

		public Criteria andPrefectureIsNotNull() {
			addCriterion("prefecture is not null");
			return (Criteria) this;
		}

		public Criteria andPrefectureEqualTo(String value) {
			addCriterion("prefecture =", value, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureNotEqualTo(String value) {
			addCriterion("prefecture <>", value, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureGreaterThan(String value) {
			addCriterion("prefecture >", value, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureGreaterThanOrEqualTo(String value) {
			addCriterion("prefecture >=", value, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureLessThan(String value) {
			addCriterion("prefecture <", value, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureLessThanOrEqualTo(String value) {
			addCriterion("prefecture <=", value, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureLike(String value) {
			addCriterion("prefecture like", value, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureNotLike(String value) {
			addCriterion("prefecture not like", value, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureIn(List<String> values) {
			addCriterion("prefecture in", values, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureNotIn(List<String> values) {
			addCriterion("prefecture not in", values, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureBetween(String value1, String value2) {
			addCriterion("prefecture between", value1, value2, "prefecture");
			return (Criteria) this;
		}

		public Criteria andPrefectureNotBetween(String value1, String value2) {
			addCriterion("prefecture not between", value1, value2, "prefecture");
			return (Criteria) this;
		}

		public Criteria andAddress1IsNull() {
			addCriterion("address1 is null");
			return (Criteria) this;
		}

		public Criteria andAddress1IsNotNull() {
			addCriterion("address1 is not null");
			return (Criteria) this;
		}

		public Criteria andAddress1EqualTo(String value) {
			addCriterion("address1 =", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1NotEqualTo(String value) {
			addCriterion("address1 <>", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1GreaterThan(String value) {
			addCriterion("address1 >", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1GreaterThanOrEqualTo(String value) {
			addCriterion("address1 >=", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1LessThan(String value) {
			addCriterion("address1 <", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1LessThanOrEqualTo(String value) {
			addCriterion("address1 <=", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1Like(String value) {
			addCriterion("address1 like", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1NotLike(String value) {
			addCriterion("address1 not like", value, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1In(List<String> values) {
			addCriterion("address1 in", values, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1NotIn(List<String> values) {
			addCriterion("address1 not in", values, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1Between(String value1, String value2) {
			addCriterion("address1 between", value1, value2, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress1NotBetween(String value1, String value2) {
			addCriterion("address1 not between", value1, value2, "address1");
			return (Criteria) this;
		}

		public Criteria andAddress2IsNull() {
			addCriterion("address2 is null");
			return (Criteria) this;
		}

		public Criteria andAddress2IsNotNull() {
			addCriterion("address2 is not null");
			return (Criteria) this;
		}

		public Criteria andAddress2EqualTo(String value) {
			addCriterion("address2 =", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2NotEqualTo(String value) {
			addCriterion("address2 <>", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2GreaterThan(String value) {
			addCriterion("address2 >", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2GreaterThanOrEqualTo(String value) {
			addCriterion("address2 >=", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2LessThan(String value) {
			addCriterion("address2 <", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2LessThanOrEqualTo(String value) {
			addCriterion("address2 <=", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2Like(String value) {
			addCriterion("address2 like", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2NotLike(String value) {
			addCriterion("address2 not like", value, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2In(List<String> values) {
			addCriterion("address2 in", values, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2NotIn(List<String> values) {
			addCriterion("address2 not in", values, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2Between(String value1, String value2) {
			addCriterion("address2 between", value1, value2, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress2NotBetween(String value1, String value2) {
			addCriterion("address2 not between", value1, value2, "address2");
			return (Criteria) this;
		}

		public Criteria andAddress3IsNull() {
			addCriterion("address3 is null");
			return (Criteria) this;
		}

		public Criteria andAddress3IsNotNull() {
			addCriterion("address3 is not null");
			return (Criteria) this;
		}

		public Criteria andAddress3EqualTo(String value) {
			addCriterion("address3 =", value, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3NotEqualTo(String value) {
			addCriterion("address3 <>", value, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3GreaterThan(String value) {
			addCriterion("address3 >", value, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3GreaterThanOrEqualTo(String value) {
			addCriterion("address3 >=", value, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3LessThan(String value) {
			addCriterion("address3 <", value, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3LessThanOrEqualTo(String value) {
			addCriterion("address3 <=", value, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3Like(String value) {
			addCriterion("address3 like", value, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3NotLike(String value) {
			addCriterion("address3 not like", value, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3In(List<String> values) {
			addCriterion("address3 in", values, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3NotIn(List<String> values) {
			addCriterion("address3 not in", values, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3Between(String value1, String value2) {
			addCriterion("address3 between", value1, value2, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress3NotBetween(String value1, String value2) {
			addCriterion("address3 not between", value1, value2, "address3");
			return (Criteria) this;
		}

		public Criteria andAddress4IsNull() {
			addCriterion("address4 is null");
			return (Criteria) this;
		}

		public Criteria andAddress4IsNotNull() {
			addCriterion("address4 is not null");
			return (Criteria) this;
		}

		public Criteria andAddress4EqualTo(String value) {
			addCriterion("address4 =", value, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4NotEqualTo(String value) {
			addCriterion("address4 <>", value, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4GreaterThan(String value) {
			addCriterion("address4 >", value, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4GreaterThanOrEqualTo(String value) {
			addCriterion("address4 >=", value, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4LessThan(String value) {
			addCriterion("address4 <", value, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4LessThanOrEqualTo(String value) {
			addCriterion("address4 <=", value, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4Like(String value) {
			addCriterion("address4 like", value, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4NotLike(String value) {
			addCriterion("address4 not like", value, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4In(List<String> values) {
			addCriterion("address4 in", values, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4NotIn(List<String> values) {
			addCriterion("address4 not in", values, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4Between(String value1, String value2) {
			addCriterion("address4 between", value1, value2, "address4");
			return (Criteria) this;
		}

		public Criteria andAddress4NotBetween(String value1, String value2) {
			addCriterion("address4 not between", value1, value2, "address4");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNull() {
			addCriterion("phone_number is null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIsNotNull() {
			addCriterion("phone_number is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberEqualTo(String value) {
			addCriterion("phone_number =", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotEqualTo(String value) {
			addCriterion("phone_number <>", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThan(String value) {
			addCriterion("phone_number >", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
			addCriterion("phone_number >=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThan(String value) {
			addCriterion("phone_number <", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
			addCriterion("phone_number <=", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberLike(String value) {
			addCriterion("phone_number like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotLike(String value) {
			addCriterion("phone_number not like", value, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberIn(List<String> values) {
			addCriterion("phone_number in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotIn(List<String> values) {
			addCriterion("phone_number not in", values, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberBetween(String value1, String value2) {
			addCriterion("phone_number between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andPhoneNumberNotBetween(String value1, String value2) {
			addCriterion("phone_number not between", value1, value2, "phoneNumber");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNull() {
			addCriterion("remarks is null");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNotNull() {
			addCriterion("remarks is not null");
			return (Criteria) this;
		}

		public Criteria andRemarksEqualTo(String value) {
			addCriterion("remarks =", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotEqualTo(String value) {
			addCriterion("remarks <>", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThan(String value) {
			addCriterion("remarks >", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(String value) {
			addCriterion("remarks >=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThan(String value) {
			addCriterion("remarks <", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThanOrEqualTo(String value) {
			addCriterion("remarks <=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLike(String value) {
			addCriterion("remarks like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotLike(String value) {
			addCriterion("remarks not like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksIn(List<String> values) {
			addCriterion("remarks in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotIn(List<String> values) {
			addCriterion("remarks not in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksBetween(String value1, String value2) {
			addCriterion("remarks between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotBetween(String value1, String value2) {
			addCriterion("remarks not between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andInsertUserIsNull() {
			addCriterion("insert_user is null");
			return (Criteria) this;
		}

		public Criteria andInsertUserIsNotNull() {
			addCriterion("insert_user is not null");
			return (Criteria) this;
		}

		public Criteria andInsertUserEqualTo(String value) {
			addCriterion("insert_user =", value, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserNotEqualTo(String value) {
			addCriterion("insert_user <>", value, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserGreaterThan(String value) {
			addCriterion("insert_user >", value, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserGreaterThanOrEqualTo(String value) {
			addCriterion("insert_user >=", value, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserLessThan(String value) {
			addCriterion("insert_user <", value, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserLessThanOrEqualTo(String value) {
			addCriterion("insert_user <=", value, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserLike(String value) {
			addCriterion("insert_user like", value, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserNotLike(String value) {
			addCriterion("insert_user not like", value, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserIn(List<String> values) {
			addCriterion("insert_user in", values, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserNotIn(List<String> values) {
			addCriterion("insert_user not in", values, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserBetween(String value1, String value2) {
			addCriterion("insert_user between", value1, value2, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertUserNotBetween(String value1, String value2) {
			addCriterion("insert_user not between", value1, value2, "insertUser");
			return (Criteria) this;
		}

		public Criteria andInsertDateIsNull() {
			addCriterion("insert_date is null");
			return (Criteria) this;
		}

		public Criteria andInsertDateIsNotNull() {
			addCriterion("insert_date is not null");
			return (Criteria) this;
		}

		public Criteria andInsertDateEqualTo(Date value) {
			addCriterion("insert_date =", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotEqualTo(Date value) {
			addCriterion("insert_date <>", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateGreaterThan(Date value) {
			addCriterion("insert_date >", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateGreaterThanOrEqualTo(Date value) {
			addCriterion("insert_date >=", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateLessThan(Date value) {
			addCriterion("insert_date <", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateLessThanOrEqualTo(Date value) {
			addCriterion("insert_date <=", value, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateIn(List<Date> values) {
			addCriterion("insert_date in", values, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotIn(List<Date> values) {
			addCriterion("insert_date not in", values, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateBetween(Date value1, Date value2) {
			addCriterion("insert_date between", value1, value2, "insertDate");
			return (Criteria) this;
		}

		public Criteria andInsertDateNotBetween(Date value1, Date value2) {
			addCriterion("insert_date not between", value1, value2, "insertDate");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNull() {
			addCriterion("update_user is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIsNotNull() {
			addCriterion("update_user is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserEqualTo(String value) {
			addCriterion("update_user =", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotEqualTo(String value) {
			addCriterion("update_user <>", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThan(String value) {
			addCriterion("update_user >", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
			addCriterion("update_user >=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThan(String value) {
			addCriterion("update_user <", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLessThanOrEqualTo(String value) {
			addCriterion("update_user <=", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserLike(String value) {
			addCriterion("update_user like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotLike(String value) {
			addCriterion("update_user not like", value, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIn(List<String> values) {
			addCriterion("update_user in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotIn(List<String> values) {
			addCriterion("update_user not in", values, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserBetween(String value1, String value2) {
			addCriterion("update_user between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateUserNotBetween(String value1, String value2) {
			addCriterion("update_user not between", value1, value2, "updateUser");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNull() {
			addCriterion("delete_flg is null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIsNotNull() {
			addCriterion("delete_flg is not null");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgEqualTo(Boolean value) {
			addCriterion("delete_flg =", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotEqualTo(Boolean value) {
			addCriterion("delete_flg <>", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThan(Boolean value) {
			addCriterion("delete_flg >", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgGreaterThanOrEqualTo(Boolean value) {
			addCriterion("delete_flg >=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThan(Boolean value) {
			addCriterion("delete_flg <", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgLessThanOrEqualTo(Boolean value) {
			addCriterion("delete_flg <=", value, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgIn(List<Boolean> values) {
			addCriterion("delete_flg in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotIn(List<Boolean> values) {
			addCriterion("delete_flg not in", values, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgBetween(Boolean value1, Boolean value2) {
			addCriterion("delete_flg between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}

		public Criteria andDeleteFlgNotBetween(Boolean value1, Boolean value2) {
			addCriterion("delete_flg not between", value1, value2, "deleteFlg");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table trn_user
	 * @mbg.generated  Sun May 16 23:31:49 JST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trn_user
     *
     * @mbg.generated do_not_delete_during_merge Thu May 13 02:26:15 JST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}